generate_game_logic_task:
  description: >
    You will create the core game mechanics and rules for a game using HTML, CSS, and JavaScript.
    Instructions
    ------------
    {game}
  expected_output: >
    Your Final answer must be the full HTML code containing the game logic, CSS, and JavaScript as close to the original as possible, only the HTML nothing else.

design_ui_task:
  description: >
    You are provided with a working HTML game. Your job is to completely revamp the CSS to enhance the user interface.
    Instructions
    ------------
    {game}
  expected_output: >
    Your Final answer must be the full HTML code containing updated CSS and JavaScript as close to the original as possible, only the HTML nothing else.

handle_user_input_task:
  description: >
    You will create code that effectively handles user interactions and controls within the game.
    Instructions
    ------------
    {game}
  expected_output: >
    Your Final answer must be the full HTML code integrating user input handling along with CSS and JavaScript as close to the original as possible, only the HTML nothing else.

integrate_code_task:
  description: >
    You are tasked with integrating various code snippets generated by different agents into a cohesive codebase.
    Instructions
    ------------
    {game}
  expected_output: >
    Your Final answer must be the full integrated HTML code containing CSS and JavaScript as close to the original as possible, only the HTML nothing else.

test_and_debug_task:
  description: >
    Using the integrated code provided, check for errors including logic errors, syntax errors, missing imports, variable declarations, mismatched brackets, and security vulnerabilities.
    Instructions
    ------------
    {game}
  expected_output: >
    Your Final answer must be the full HTML code with corrected errors containing CSS and JavaScript as close to the original as possible, only the HTML nothing else.
